apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ronro-pilot-audio
  labels:
    app.kubernetes.io/name: ronro
    app.kubernetes.io/component: private-pilot-audio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
