apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ronro-pilot-evaluation
  labels:
    app.kubernetes.io/name: ronro
    app.kubernetes.io/component: evaluation-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
