apiVersion: v1
kind: Service
metadata:
  name: discussion-map-pilot
  labels:
    app.kubernetes.io/name: discussion-map-ai-facilitator
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: discussion-map-ai-facilitator
    app.kubernetes.io/part-of: discussion-map-pilot
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
    - name: websocket
      port: 8765
      targetPort: websocket
      protocol: TCP
