apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ronro-pilot

resources:
  - ../base

images:
  - name: registry.example.invalid/ronro
    newName: registry.example.invalid/ronro
    newTag: pilot-001
