apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: discussion-map-pilot

resources:
  - ../../base

images:
  - name: registry.example.invalid/discussion-map-ai-facilitator
    newName: ghcr.io/hakobune8/ronro
    digest: sha256:f604803515bcb021f3262fe6c5713a610796224663df84dd5b47497324a17118

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
  - path: ingress-patch.yaml
