apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: discussion-map-pilot

resources:
  - ../../base

images:
  - name: registry.example.invalid/discussion-map-ai-facilitator
    newName: ghcr.io/hakobune8/ronro
    digest: sha256:45b14e83ded85180d6392cd8dd1ac96a6d79c12482a87029500638f148c456c8

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
  - path: ingress-patch.yaml
